/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ThothfoodRouteRouteImport } from './routes/thothfood/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThothfoodIndexRouteImport } from './routes/thothfood/index'
import { Route as ThothfoodRestaurantsRouteImport } from './routes/thothfood/restaurants'
import { Route as ThothfoodPricingRouteImport } from './routes/thothfood/pricing'
import { Route as ThothfoodHowItWorksRouteImport } from './routes/thothfood/how-it-works'
import { Route as ThothfoodContactRouteImport } from './routes/thothfood/contact'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ThothfoodRouteRoute = ThothfoodRouteRouteImport.update({
  id: '/thothfood',
  path: '/thothfood',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThothfoodIndexRoute = ThothfoodIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThothfoodRouteRoute,
} as any)
const ThothfoodRestaurantsRoute = ThothfoodRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => ThothfoodRouteRoute,
} as any)
const ThothfoodPricingRoute = ThothfoodPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => ThothfoodRouteRoute,
} as any)
const ThothfoodHowItWorksRoute = ThothfoodHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => ThothfoodRouteRoute,
} as any)
const ThothfoodContactRoute = ThothfoodContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ThothfoodRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/thothfood': typeof ThothfoodRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thothfood/contact': typeof ThothfoodContactRoute
  '/thothfood/how-it-works': typeof ThothfoodHowItWorksRoute
  '/thothfood/pricing': typeof ThothfoodPricingRoute
  '/thothfood/restaurants': typeof ThothfoodRestaurantsRoute
  '/thothfood/': typeof ThothfoodIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thothfood/contact': typeof ThothfoodContactRoute
  '/thothfood/how-it-works': typeof ThothfoodHowItWorksRoute
  '/thothfood/pricing': typeof ThothfoodPricingRoute
  '/thothfood/restaurants': typeof ThothfoodRestaurantsRoute
  '/thothfood': typeof ThothfoodIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/thothfood': typeof ThothfoodRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thothfood/contact': typeof ThothfoodContactRoute
  '/thothfood/how-it-works': typeof ThothfoodHowItWorksRoute
  '/thothfood/pricing': typeof ThothfoodPricingRoute
  '/thothfood/restaurants': typeof ThothfoodRestaurantsRoute
  '/thothfood/': typeof ThothfoodIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/thothfood'
    | '/sitemap.xml'
    | '/thothfood/contact'
    | '/thothfood/how-it-works'
    | '/thothfood/pricing'
    | '/thothfood/restaurants'
    | '/thothfood/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/thothfood/contact'
    | '/thothfood/how-it-works'
    | '/thothfood/pricing'
    | '/thothfood/restaurants'
    | '/thothfood'
  id:
    | '__root__'
    | '/'
    | '/thothfood'
    | '/sitemap.xml'
    | '/thothfood/contact'
    | '/thothfood/how-it-works'
    | '/thothfood/pricing'
    | '/thothfood/restaurants'
    | '/thothfood/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThothfoodRouteRoute: typeof ThothfoodRouteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thothfood': {
      id: '/thothfood'
      path: '/thothfood'
      fullPath: '/thothfood'
      preLoaderRoute: typeof ThothfoodRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thothfood/': {
      id: '/thothfood/'
      path: '/'
      fullPath: '/thothfood/'
      preLoaderRoute: typeof ThothfoodIndexRouteImport
      parentRoute: typeof ThothfoodRouteRoute
    }
    '/thothfood/restaurants': {
      id: '/thothfood/restaurants'
      path: '/restaurants'
      fullPath: '/thothfood/restaurants'
      preLoaderRoute: typeof ThothfoodRestaurantsRouteImport
      parentRoute: typeof ThothfoodRouteRoute
    }
    '/thothfood/pricing': {
      id: '/thothfood/pricing'
      path: '/pricing'
      fullPath: '/thothfood/pricing'
      preLoaderRoute: typeof ThothfoodPricingRouteImport
      parentRoute: typeof ThothfoodRouteRoute
    }
    '/thothfood/how-it-works': {
      id: '/thothfood/how-it-works'
      path: '/how-it-works'
      fullPath: '/thothfood/how-it-works'
      preLoaderRoute: typeof ThothfoodHowItWorksRouteImport
      parentRoute: typeof ThothfoodRouteRoute
    }
    '/thothfood/contact': {
      id: '/thothfood/contact'
      path: '/contact'
      fullPath: '/thothfood/contact'
      preLoaderRoute: typeof ThothfoodContactRouteImport
      parentRoute: typeof ThothfoodRouteRoute
    }
  }
}

interface ThothfoodRouteRouteChildren {
  ThothfoodContactRoute: typeof ThothfoodContactRoute
  ThothfoodHowItWorksRoute: typeof ThothfoodHowItWorksRoute
  ThothfoodPricingRoute: typeof ThothfoodPricingRoute
  ThothfoodRestaurantsRoute: typeof ThothfoodRestaurantsRoute
  ThothfoodIndexRoute: typeof ThothfoodIndexRoute
}

const ThothfoodRouteRouteChildren: ThothfoodRouteRouteChildren = {
  ThothfoodContactRoute: ThothfoodContactRoute,
  ThothfoodHowItWorksRoute: ThothfoodHowItWorksRoute,
  ThothfoodPricingRoute: ThothfoodPricingRoute,
  ThothfoodRestaurantsRoute: ThothfoodRestaurantsRoute,
  ThothfoodIndexRoute: ThothfoodIndexRoute,
}

const ThothfoodRouteRouteWithChildren = ThothfoodRouteRoute._addFileChildren(
  ThothfoodRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThothfoodRouteRoute: ThothfoodRouteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
